generatorOptions:
  disableNameSuffixHash: true

bases:
  - ../../components/services/overlays/dev

namespace: maroonteam-dev

commonLabels:
  environment: dev
  team: maroon

resources:
  - namespace.yml

secretGenerator:
  - name: gateway-service-secret
    env: "./.tmp/gateway-service-secret.env"
  - name: user-service-secret
    env: "./.tmp/user-service-secret.env"
  - name: survey-service-secret
    env: "./.tmp/survey-service-secret.env"

images:
  - name: mern-services-image
    newName: 782259420937.dkr.ecr.us-east-1.amazonaws.com/hackathon/maroonteam
    newTag: latest