name: DEV-CI

on:
  pull_request:
    branches: [main]
  
jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        locations: [
          { "name": "gateway-service", "pwd": "./mern-stack/gateway-service" },
          { "name": "user-service", "pwd": "./mern-stack/user-service" },
          { "name": "survey-service", "pwd": "./mern-stack/survey-service" },
          { "name": "react-app", "pwd": "./mern-stack/react-app" }
        ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v2

      - name: ${{ matrix.locations.name }} - install nodejs dependencies
        working-directory: ${{ matrix.locations.pwd }}
        run: npm install

      - name: ${{ matrix.locations.name }} - build
        working-directory: ${{ matrix.locations.pwd }}
        run: npm run build --if-present

      - name: ${{ matrix.locations.name }} - test
        working-directory: ${{ matrix.locations.pwd }}
        run: npm test